from manim import *
import numpy as np

class Taylor(Scene):
    def construct(self):
        text=Text("TAYLOR SERIES - (Cos(x))",color=BLUE,font_size=48,t2c={'(Cos(x)':RED}, disable_ligatures=True)
        self.play(Write(text))
        self.wait()
        self.play(Unwrite(text,reverse=False))
        self.wait()
        axes=Axes(x_range=(-7,7),y_range=(-2,2),x_length=13,y_length=3,tips=False).add_coordinates().set_color(BLUE)
        x=axes.get_x_axis_label("X").set_color(GREEN)
        y=axes.get_y_axis_label("Y").set_color(GREEN)
        self.play(Write(axes),Write(x),Write(y))
        curve1=axes.plot(lambda x: np.cos(x),color=RED)
        curve1_label = axes.get_graph_label(curve1, label='cos(x)',direction=UR,buff=0.6)
        curve2=axes.plot(lambda x: 1,color=YELLOW)
        curve2_label = axes.get_graph_label(curve2, label='1')
        curve3=axes.plot(lambda x: 1-x**2/2,color=YELLOW)
        curve3_label = axes.get_graph_label(curve3, label='1-(x^{2}/2!)')
        curve4=axes.plot(lambda x: 1-x**2/2+x**4/24,color=YELLOW)
        curve4_label = axes.get_graph_label(curve4, label='1-(x^{2}/2)+(x^{4}/4!)')
        curve5=axes.plot(lambda x: 1-x**2/2+x**4/24-x**6/720,color=YELLOW)
        curve5_label = axes.get_graph_label(curve5, label='1-(x^{2}/2)+(x^{4}/24)-(x^{6}/6!)')
        self.play(Write(curve1),Write(curve1_label))
        self.wait()
        self.play(Create(curve2),Write(curve2_label))
        self.wait()
        self.play(ReplacementTransform(curve2,curve3),ReplacementTransform(curve2_label,curve3_label))
        self.wait()
        self.play(ReplacementTransform(curve3,curve4),ReplacementTransform(curve3_label,curve4_label))
        self.wait()
        self.play(ReplacementTransform(curve4,curve5),ReplacementTransform(curve4_label,curve5_label))
        self.wait(2)